#!/bin/bash
#=======================
# Author : Ali Moradzade
# Created: 2022/01/20
#=======================

#standardize names

for directory in *
do
	if [ -d "$directory" ]
	then
		rename 's/ +/-/g; y/A-Z/a-z/' "$directory"
		rename 's/-+/-/g' "$directory"
	fi
done
