#!/bin/bash
#=======================
# Author : Ali Moradzade
# Created: 2022/09/10
#=======================

#stands

count=1
for f in *.ipynb
do
	if [ -f "$f" ]
	then
		rename "s/^(\d+)/sprintf('%02d', $count)/e" "$f"
		((count++))
	fi
done
